### PR TITLE
REST: upgrade Restlet from 2.0 to 2.1

### PR DESCRIPTION
**Pull request by eskatos**
Had to fix some minor compilation errors in `librairies/rest`. Works OK.

But, RssReaderTest in `libraries/rest-client` now behave badly and takes age to complete (recoverable error / refresh cycles).
Note that I did not change any code in the `librairies/rest-[common|client|server]` modules and that `librairies/rest` is a different thing.

Could anybody with more Restlet practice than me take a look please?

Cheers

/Paul

### CODE REVIEW

**Comment by tbml** [comment]
Seems that internal Restlet client has problem to read from HTTPS resource.
When I replaced line 75 with

``` java
                        return documentBuilderFactory.newDocumentBuilder().parse(
                                new InputSource(new InputStreamReader( response.getEntity().getStream())) );
```

test passed, but it still randomly freeze.

**Comment by eskatos** [comment]
Yep I tried to consume the entity as String before passing it to the parse method with about the same behaviour.

To me it looks like the Restlet internal client is misbehaving but I'm not a regular Restlet user so ... 
What about using HttpClient backend ?

**Comment by niclash** [comment]
I haven't looked at the code yet, but I know there is a bug in the default
server(!), which somehow makes the client not receive all the data and
therefor hangs, even a browser will have that behavior. The only "work
around" is to follow their advice "Don't use it" and instead put a Jetty
server in front of it.

I'll take care of it during this week.

Niclas

On Tue, Oct 22, 2013 at 1:17 AM, Paul Merlin notifications@github.comwrote:

> Yep I tried to consume the entity as String before passing it to the parse
> method with about the same behaviour.
> 
> To me it looks like the Restlet internal client is misbehaving but I'm not
> a regular Restlet user so ...
> What about using HttpClient backend ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Qi4j/qi4j-sdk/pull/18#issuecomment-26736955
> .

## 

Niclas Hedhman, Software Developer
河南南路555弄15号1901室。
http://www.qi4j.org - New Energy for Java

I live here; http://tinyurl.com/3xugrbk
I work here; http://tinyurl.com/6a2pl4j
I relax here; http://tinyurl.com/2cgsug

**Comment by eskatos** [comment]
The incriminated test use the Restlet Client only, not the server, as it directly fetches a Github feed and parse it.
BTW, this is, as far as I remember, the only test of the SDK that need connectivity to pass.

**Comment by niclash** [comment]
I recall something connecting to google.com

**Pull request closed without merging**
