### PR TITLE
dci-cargo samples migration to 2.0

### PR DESCRIPTION
**Pull request by tbml**

### CODE REVIEW

**Comment by tbml** [comment]
Assembler registeres DCISampleApplication_a.class instead of WicketQi4jApplication as I was not able to find a way how to inject into it.

EntityToDTOService should be reviewed if it follows original intent.

rest was mainly simple api changes

**Comment by eskatos** [comment]
Hi Tibor,

First, thanks for the pull-request!

I see no pb in what you did about the WicketQi4jApplication injection.
Like Niclas wrote on the list the EntityToDTOService thing is not so important because it will have to be refactored once we get toValue() support in core.

Now, this pull-request is only about dcisample_a. We should work a little bit more on this to get dcisample_b running on Qi4j develop branch too. Integrating the build with the gradle build system should be done too.

If you are ok I can give a hand about the build system. Applying changes to dcisample_b should not be too much hassle for you now that you went through dcisample_a.

For doing this you can add me as a contributor to your qi4j-sdk fork. We then work on your repository and this pull-request will get automatically updated with subsequents commits.

We'll merge the pull-request once it's ready.

Best regards

/Paul

**Comment by tbml** [comment]
- sample_b migrated
- envisage tool compilation fixed ( havent tried if tool actually works )
- build.gradle added for samples
  fixed libraries in sdk
  I am able to run gradlw idea, open project and run Start808x runners
  there is build file for each sample as there are the same packages and cannot be compiled at once

**Comment by eskatos** [comment]
I fixed unit test tearDown in both dcisample_a and dcisample_b.

All unit tests in dcisample_a pass \o/

Only 11% of the unit tests in dcisample_b pass :-(

Something is wrong about UoW handling: java.lang.IllegalStateException: No current UnitOfWork active

I've tried to "blindly" add uowf.newUnitOfWork() calls but couldn't easily find where the problem is.

Could you take a look?

**Comment by tbml** [comment]
now only 5 from 111 sample_b tests fails

**Comment by tbml** [comment]
looking at the one of failed test (RegisterHandlingEventTest - deviation_4a_DuplicateEvent_Receive) 
and it seems that it can be related to nested uow functionality that was removed in 2.0
( actually I am not sure if nested uow was working in previous version and how )

**Comment by eskatos** [comment]
Maybe completely removing nested UoW in tests would simplify things but I don't know theses samples very well and don't know if it's easily feasible.

2.0 nested UoWs work like the following: the outer UoW is paused/resumed around the inner one.

Hope this helps.

BTW I get this here:

```
Test com.marcgrue.dcisample_b.context.test.handling.inspection.event.InspectLoadedCargoTest FAILED
Test com.marcgrue.dcisample_b.context.test.handling.registration.RegisterHandlingEventTest FAILED
112 tests completed, 7 failures
```

**Comment by tbml** [comment]
now 48 sample_a and 111 sample_b tests pass for me. 

RdfIndexingService that is used by tests was not activated and indexing was simply not working. It quitely failed at line 86 (RdfIndexingService). I don't know internals of activation system yet, so I have simply fixed it by starting on startup.

Uow handling fixes: Query  can see only commited changes ( after uow.complete ) . So new uow need to be started in some tests. I am confused why it worked in v1.4.

**Comment by eskatos** [comment]
Excellent!
Thanks a lot Tibor.

**Pull request merged**
